In [1]:
ifgdates = [
    '20230101_20230110',  # Interferogram from t1 → t2
    '20230110_20230120',  # Interferogram from t2 → t3
    '20230101_20230120',  # Interferogram from t1 → t3 (spanning two time intervals)
    '20230120_20230130',  # Interferogram from t3 → t4
    '20230110_20230130',  # Interferogram from t2 → t4
]

# Define imdates manually for debugging
imdates = ['20230101', '20230110', '20230120', '20230130']

In [10]:
import LiCSBAS_tools_lib as tools_lib
ifgdates = ['20230209_20230221', '20230209_20230305', '20230209_20230410', '20230209_20230422', '20230221_20230305', '20230221_20230410', '20230221_20230422', '20230221_20230504', '20230305_20230410', '20230305_20230422', '20230305_20230504', '20230305_20230516', '20230305_20230609', '20230305_20230621', '20230305_20230901', '20230305_20230913', '20230305_20230925', '20230305_20240311', '20230305_20240323', '20230410_20230422', '20230410_20230504', '20230410_20230516', '20230410_20230528', '20230422_20230504', '20230422_20230516', '20230422_20230528', '20230422_20230609', '20230504_20230516', '20230504_20230528', '20230504_20230609', '20230504_20230621', '20230516_20230528', '20230516_20230609', '20230516_20230621', '20230516_20230703', '20230528_20230609', '20230528_20230621', '20230528_20230703', '20230528_20230715', '20230609_20230621', '20230609_20230703', '20230609_20230715', '20230609_20230727', '20230609_20230901', '20230609_20230913', '20230609_20230925', '20230609_20240311', '20230609_20240323', '20230609_20240603', '20230609_20240615', '20230609_20240627', '20230621_20230703', '20230621_20230715', '20230621_20230727', '20230621_20230808', '20230621_20230901', '20230621_20230913', '20230621_20230925', '20230621_20240311', '20230621_20240323', '20230621_20240603', '20230621_20240615', '20230621_20240627', '20230703_20230715', '20230703_20230727', '20230703_20230808', '20230703_20230820', '20230715_20230727', '20230715_20230808', '20230715_20230820', '20230715_20230901', '20230727_20230808', '20230727_20230820', '20230727_20230901', '20230727_20230913', '20230808_20230820', '20230808_20230901', '20230808_20230913', '20230808_20230925', '20230820_20230901', '20230820_20230913', '20230820_20230925', '20230820_20231007', '20230901_20230913', '20230901_20230925', '20230901_20231007', '20230901_20231019', '20230901_20240311', '20230901_20240323', '20230901_20240603', '20230901_20240615', '20230901_20240627', '20230901_20240907', '20230901_20240919', '20230913_20230925', '20230913_20231007', '20230913_20231019', '20230913_20231031', '20230913_20240311', '20230913_20240323', '20230913_20240603', '20230913_20240615', '20230913_20240627', '20230913_20240907', '20230913_20240919', '20230925_20231007', '20230925_20231019', '20230925_20231031', '20230925_20231112', '20230925_20240311', '20230925_20240323', '20230925_20240603', '20230925_20240615', '20230925_20240627', '20230925_20240907', '20230925_20240919', '20231007_20231019', '20231007_20231031', '20231007_20231112', '20231007_20231124', '20231019_20231031', '20231019_20231112', '20231019_20231124', '20231019_20231206', '20231031_20231112', '20231031_20231124', '20231031_20231206', '20231031_20231218', '20231112_20231124', '20231112_20231206', '20231112_20231218', '20231112_20231230', '20231112_20240111', '20231124_20231206', '20231124_20231218', '20231124_20231230', '20231124_20240111', '20231206_20231218', '20231206_20231230', '20231206_20240111', '20231206_20240123', '20231218_20231230', '20231218_20240111', '20231218_20240123', '20231218_20240204', '20231230_20240111', '20231230_20240123', '20231230_20240204', '20231230_20240216', '20240111_20240123', '20240111_20240204', '20240111_20240216', '20240111_20240228', '20240123_20240204', '20240123_20240216', '20240123_20240228', '20240123_20240311', '20240204_20240216', '20240204_20240228', '20240204_20240311', '20240204_20240323', '20240216_20240228', '20240216_20240311', '20240216_20240323', '20240216_20240404', '20240228_20240311', '20240228_20240323', '20240228_20240404', '20240228_20240416', '20240311_20240323', '20240311_20240404', '20240311_20240416', '20240311_20240428', '20240311_20240603', '20240311_20240615', '20240311_20240627', '20240311_20240907', '20240311_20240919', '20240323_20240404', '20240323_20240416', '20240323_20240428', '20240323_20240510', '20240323_20240603', '20240323_20240615', '20240323_20240627', '20240323_20240907', '20240323_20240919', '20240404_20240416', '20240404_20240428', '20240404_20240510', '20240404_20240522', '20240416_20240428', '20240416_20240510', '20240416_20240522', '20240416_20240603', '20240428_20240510', '20240428_20240522', '20240428_20240603', '20240428_20240615', '20240510_20240522', '20240510_20240603', '20240510_20240615', '20240510_20240627', '20240522_20240603', '20240522_20240615', '20240522_20240627', '20240522_20240709', '20240603_20240615', '20240603_20240627', '20240603_20240709', '20240603_20240721', '20240603_20240907', '20240603_20240919', '20240615_20240627', '20240615_20240709', '20240615_20240721', '20240615_20240802', '20240615_20240907', '20240615_20240919', '20240627_20240709', '20240627_20240721', '20240627_20240802', '20240627_20240814', '20240627_20240907', '20240627_20240919', '20240709_20240721', '20240709_20240802', '20240709_20240814', '20240709_20240826', '20240721_20240802', '20240721_20240814', '20240721_20240826', '20240721_20240907', '20240802_20240814', '20240802_20240826', '20240802_20240907', '20240802_20240919', '20240814_20240826', '20240814_20240907', '20240814_20240919', '20240814_20241001', '20240826_20240907', '20240826_20240919', '20240826_20241001', '20240826_20241013', '20240907_20240919', '20240907_20241001', '20240907_20241013', '20240907_20241025', '20240919_20241001', '20240919_20241013', '20240919_20241025', '20240919_20241106', '20241001_20241013', '20241001_20241025', '20241001_20241106', '20241013_20241025', '20241013_20241106', '20241025_20241106']
imdates = tools_lib.ifgdates2imdates(ifgdates)

In [11]:
import numpy as np

def make_sb_matrix(ifgdates, imdates):
    n_im = len(imdates)
    n_ifg = len(ifgdates)
    
    G = np.zeros((n_ifg, n_im-1), dtype=np.int16)
    
    for ifgix, ifgd in enumerate(ifgdates):
        primarydate = ifgd[:8]
        primaryix = imdates.index(primarydate)
        secondarydate = ifgd[-8:]
        secondaryix = imdates.index(secondarydate)
        G[ifgix, primaryix:secondaryix] = 1
    
    return G


def make_loop_matrix(ifgdates):
    """
    Make loop matrix (containing 1, -1, 0) from ifgdates.

    Inputs:
      ifgdates : Unwrapped phase vector at a point without nan (n_ifg)

    Returns:
      Aloop : Loop matrix with 1 for ifg12/ifg23 and -1 for ifg13
              (n_loop, n_ifg)

    """
    n_ifg = len(ifgdates)
    Aloop = []

    for ix_ifg12, ifgd12 in enumerate(ifgdates):
        primary12 = ifgd12[0:8]
        secondary12 = ifgd12[9:17]
        ifgdates23 = [ ifgd for ifgd in ifgdates if
                      ifgd.startswith(secondary12)] # all candidates of ifg23

        for ifgd23 in ifgdates23: # for each candidate of ifg23
            secondary23 = ifgd23[9:17]
            try:
                ## Search ifg13
                ix_ifg13 = ifgdates.index(primary12+'_'+secondary23)
            except: # no loop for this ifg23. Next.
                continue

            ## Loop found
            ix_ifg23 = ifgdates.index(ifgd23)

            Aline = [0]*n_ifg
            Aline[ix_ifg12] = 1
            Aline[ix_ifg23] = 1
            Aline[ix_ifg13] = -1
            Aloop.append(Aline)

    Aloop = np.array(Aloop)

    return Aloop


# Generate G matrix
G = make_sb_matrix(ifgdates, imdates)

# Print results
print("G Matrix:\n", G)

G Matrix:
 [[1 0 0 ..., 0 0 0]
 [1 1 0 ..., 0 0 0]
 [1 1 1 ..., 0 0 0]
 ..., 
 [0 0 0 ..., 0 1 0]
 [0 0 0 ..., 0 1 1]
 [0 0 0 ..., 0 0 1]]


In [23]:
print(len(ifgdates), len(imdates))
Aloop.shape
Aloop[3:5, :]

259 52


array([[ 0,  1, -1,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0, 

In [3]:
import numpy as np

# Example matrix (each row represents a pixel's data across interferograms)
unwpatch = np.array([
    [10, 20, np.nan, 30],  # 3 valid
    [np.nan, np.nan, np.nan, np.nan],  # 0 valid
    [5, 15, 25, 35],  # 4 valid
    [np.nan, 10, np.nan, 20]  # 2 valid
])

n_unw_thre = 3  # Minimum required valid values

# Find rows where the number of valid values > threshold
ix_unnan_pt = np.where(np.sum(~np.isnan(unwpatch), axis=1) > n_unw_thre)
print(ix_unnan_pt)  

(array([2]),)


In [2]:
ix_unnan_pt

array([2])

In [4]:
n_para_gap = int(np.floor(112496/1000))

In [9]:
np.floor(1129/10)

112.0